version: "2.0"
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: qwerty
    networks:
     - net
  consumer:
    build: ./consumer
    depends_on:
     - send
    networks:
     - net
    depends_on:
     - rabbitmq
     - db

  producer:
    build: ./producer
    networks:
     - net
    depends_on:
     - rabbitmq
     - db


  rabbitmq:
    image: rabbitmq
    networks:
     - net


networks:
 net:
    
